package com.newcore.batch.platform.persistence;

import com.newcore.batch.platform.model.po.BatchTask;
import com.newcore.batch.platform.model.po.BatchTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int countByExample(BatchTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByExample(BatchTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByPrimaryKey(Long batchTaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insert(BatchTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insertSelective(BatchTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    List<BatchTask> selectByExample(BatchTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    BatchTask selectByPrimaryKey(Long batchTaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") BatchTask record, @Param("example") BatchTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExample(@Param("record") BatchTask record, @Param("example") BatchTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKeySelective(BatchTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKey(BatchTask record);
}