package com.newcore.batch.platform.persistence;

import com.newcore.batch.platform.model.po.BatchAccount;
import com.newcore.batch.platform.model.po.BatchAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int countByExample(BatchAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByExample(BatchAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insert(BatchAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insertSelective(BatchAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    List<BatchAccount> selectByExample(BatchAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    BatchAccount selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") BatchAccount record, @Param("example") BatchAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExample(@Param("record") BatchAccount record, @Param("example") BatchAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKeySelective(BatchAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKey(BatchAccount record);
}