package com.newcore.batch.platform.persistence;

import com.newcore.batch.platform.model.po.BatchWorkFlowTask;
import com.newcore.batch.platform.model.po.BatchWorkFlowTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchWorkFlowTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int countByExample(BatchWorkFlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByExample(BatchWorkFlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByPrimaryKey(Long workFlowTaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insert(BatchWorkFlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insertSelective(BatchWorkFlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    List<BatchWorkFlowTask> selectByExample(BatchWorkFlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    BatchWorkFlowTask selectByPrimaryKey(Long workFlowTaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") BatchWorkFlowTask record, @Param("example") BatchWorkFlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExample(@Param("record") BatchWorkFlowTask record, @Param("example") BatchWorkFlowTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKeySelective(BatchWorkFlowTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_work_flow_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKey(BatchWorkFlowTask record);
}