package com.newcore.batch.platform.persistence;

import com.newcore.batch.platform.model.po.BatchExecHistory;
import com.newcore.batch.platform.model.po.BatchExecHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchExecHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int countByExample(BatchExecHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByExample(BatchExecHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByPrimaryKey(Long batchExecuteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insert(BatchExecHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insertSelective(BatchExecHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    List<BatchExecHistory> selectByExample(BatchExecHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    BatchExecHistory selectByPrimaryKey(Long batchExecuteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") BatchExecHistory record, @Param("example") BatchExecHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExample(@Param("record") BatchExecHistory record, @Param("example") BatchExecHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKeySelective(BatchExecHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKey(BatchExecHistory record);
}