package com.newcore.batch.platform.persistence;

import com.newcore.batch.platform.model.po.BatchExportTask;
import com.newcore.batch.platform.model.po.BatchExportTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchExportTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int countByExample(BatchExportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByExample(BatchExportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByPrimaryKey(Long batchExportTaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insert(BatchExportTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insertSelective(BatchExportTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    List<BatchExportTask> selectByExample(BatchExportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    BatchExportTask selectByPrimaryKey(Long batchExportTaskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") BatchExportTask record, @Param("example") BatchExportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExample(@Param("record") BatchExportTask record, @Param("example") BatchExportTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKeySelective(BatchExportTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKey(BatchExportTask record);
}