package com.newcore.batch.platform.persistence;

import com.newcore.batch.platform.model.po.BatchDatasourceConfig;
import com.newcore.batch.platform.model.po.BatchDatasourceConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchDatasourceConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int countByExample(BatchDatasourceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByExample(BatchDatasourceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int deleteByPrimaryKey(String batchDatasourceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insert(BatchDatasourceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int insertSelective(BatchDatasourceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    List<BatchDatasourceConfig> selectByExample(BatchDatasourceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    BatchDatasourceConfig selectByPrimaryKey(String batchDatasourceCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") BatchDatasourceConfig record, @Param("example") BatchDatasourceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByExample(@Param("record") BatchDatasourceConfig record, @Param("example") BatchDatasourceConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKeySelective(BatchDatasourceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    int updateByPrimaryKey(BatchDatasourceConfig record);
}