package com.newcore.batch.platform.model.po;

import java.io.Serializable;
import java.util.Date;

public class BatchDatasourceConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_datasource_config.batch_datasource_code
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String batchDatasourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_datasource_config.batch_datasource_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String batchDatasourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_datasource_config.datasource_url
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String datasourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_datasource_config.datasource_connect_username
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String datasourceConnectUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_datasource_config.datasource_connect_password
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String datasourceConnectPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_datasource_config.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_datasource_config.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_datasource_config.batch_datasource_code
     *
     * @return the value of batch_datasource_config.batch_datasource_code
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getBatchDatasourceCode() {
        return batchDatasourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_datasource_config.batch_datasource_code
     *
     * @param batchDatasourceCode the value for batch_datasource_config.batch_datasource_code
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setBatchDatasourceCode(String batchDatasourceCode) {
        this.batchDatasourceCode = batchDatasourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_datasource_config.batch_datasource_name
     *
     * @return the value of batch_datasource_config.batch_datasource_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getBatchDatasourceName() {
        return batchDatasourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_datasource_config.batch_datasource_name
     *
     * @param batchDatasourceName the value for batch_datasource_config.batch_datasource_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setBatchDatasourceName(String batchDatasourceName) {
        this.batchDatasourceName = batchDatasourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_datasource_config.datasource_url
     *
     * @return the value of batch_datasource_config.datasource_url
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getDatasourceUrl() {
        return datasourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_datasource_config.datasource_url
     *
     * @param datasourceUrl the value for batch_datasource_config.datasource_url
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setDatasourceUrl(String datasourceUrl) {
        this.datasourceUrl = datasourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_datasource_config.datasource_connect_username
     *
     * @return the value of batch_datasource_config.datasource_connect_username
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getDatasourceConnectUsername() {
        return datasourceConnectUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_datasource_config.datasource_connect_username
     *
     * @param datasourceConnectUsername the value for batch_datasource_config.datasource_connect_username
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setDatasourceConnectUsername(String datasourceConnectUsername) {
        this.datasourceConnectUsername = datasourceConnectUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_datasource_config.datasource_connect_password
     *
     * @return the value of batch_datasource_config.datasource_connect_password
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getDatasourceConnectPassword() {
        return datasourceConnectPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_datasource_config.datasource_connect_password
     *
     * @param datasourceConnectPassword the value for batch_datasource_config.datasource_connect_password
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setDatasourceConnectPassword(String datasourceConnectPassword) {
        this.datasourceConnectPassword = datasourceConnectPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_datasource_config.create_time
     *
     * @return the value of batch_datasource_config.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_datasource_config.create_time
     *
     * @param createTime the value for batch_datasource_config.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_datasource_config.update_time
     *
     * @return the value of batch_datasource_config.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_datasource_config.update_time
     *
     * @param updateTime the value for batch_datasource_config.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_datasource_config
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", batchDatasourceCode=").append(batchDatasourceCode);
        sb.append(", batchDatasourceName=").append(batchDatasourceName);
        sb.append(", datasourceUrl=").append(datasourceUrl);
        sb.append(", datasourceConnectUsername=").append(datasourceConnectUsername);
        sb.append(", datasourceConnectPassword=").append(datasourceConnectPassword);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}