package com.newcore.batch.platform.model.po;

import java.io.Serializable;
import java.util.Date;

public class BatchAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_account.user_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_account.user_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_account.user_password
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_account.user_status
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_account.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_account.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_account.user_id
     *
     * @return the value of batch_account.user_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_account.user_id
     *
     * @param userId the value for batch_account.user_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_account.user_name
     *
     * @return the value of batch_account.user_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_account.user_name
     *
     * @param userName the value for batch_account.user_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_account.user_password
     *
     * @return the value of batch_account.user_password
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_account.user_password
     *
     * @param userPassword the value for batch_account.user_password
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_account.user_status
     *
     * @return the value of batch_account.user_status
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_account.user_status
     *
     * @param userStatus the value for batch_account.user_status
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_account.create_time
     *
     * @return the value of batch_account.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_account.create_time
     *
     * @param createTime the value for batch_account.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_account.update_time
     *
     * @return the value of batch_account.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_account.update_time
     *
     * @param updateTime the value for batch_account.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_account
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", userPassword=").append(userPassword);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}