package com.newcore.batch.platform.model.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BatchExecHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.batch_execute_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Long batchExecuteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.batch_task_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Long batchTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.task_execute_start_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date taskExecuteStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.task_execute_end_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date taskExecuteEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.task_execute_duration_unit
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String taskExecuteDurationUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.task_execute_duration
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private BigDecimal taskExecuteDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_exec_history.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.batch_execute_id
     *
     * @return the value of batch_exec_history.batch_execute_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Long getBatchExecuteId() {
        return batchExecuteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.batch_execute_id
     *
     * @param batchExecuteId the value for batch_exec_history.batch_execute_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setBatchExecuteId(Long batchExecuteId) {
        this.batchExecuteId = batchExecuteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.batch_task_id
     *
     * @return the value of batch_exec_history.batch_task_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Long getBatchTaskId() {
        return batchTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.batch_task_id
     *
     * @param batchTaskId the value for batch_exec_history.batch_task_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setBatchTaskId(Long batchTaskId) {
        this.batchTaskId = batchTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.task_execute_start_time
     *
     * @return the value of batch_exec_history.task_execute_start_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getTaskExecuteStartTime() {
        return taskExecuteStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.task_execute_start_time
     *
     * @param taskExecuteStartTime the value for batch_exec_history.task_execute_start_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setTaskExecuteStartTime(Date taskExecuteStartTime) {
        this.taskExecuteStartTime = taskExecuteStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.task_execute_end_time
     *
     * @return the value of batch_exec_history.task_execute_end_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getTaskExecuteEndTime() {
        return taskExecuteEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.task_execute_end_time
     *
     * @param taskExecuteEndTime the value for batch_exec_history.task_execute_end_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setTaskExecuteEndTime(Date taskExecuteEndTime) {
        this.taskExecuteEndTime = taskExecuteEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.task_execute_duration_unit
     *
     * @return the value of batch_exec_history.task_execute_duration_unit
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getTaskExecuteDurationUnit() {
        return taskExecuteDurationUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.task_execute_duration_unit
     *
     * @param taskExecuteDurationUnit the value for batch_exec_history.task_execute_duration_unit
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setTaskExecuteDurationUnit(String taskExecuteDurationUnit) {
        this.taskExecuteDurationUnit = taskExecuteDurationUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.task_execute_duration
     *
     * @return the value of batch_exec_history.task_execute_duration
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public BigDecimal getTaskExecuteDuration() {
        return taskExecuteDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.task_execute_duration
     *
     * @param taskExecuteDuration the value for batch_exec_history.task_execute_duration
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setTaskExecuteDuration(BigDecimal taskExecuteDuration) {
        this.taskExecuteDuration = taskExecuteDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.create_time
     *
     * @return the value of batch_exec_history.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.create_time
     *
     * @param createTime the value for batch_exec_history.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_exec_history.update_time
     *
     * @return the value of batch_exec_history.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_exec_history.update_time
     *
     * @param updateTime the value for batch_exec_history.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_exec_history
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", batchExecuteId=").append(batchExecuteId);
        sb.append(", batchTaskId=").append(batchTaskId);
        sb.append(", taskExecuteStartTime=").append(taskExecuteStartTime);
        sb.append(", taskExecuteEndTime=").append(taskExecuteEndTime);
        sb.append(", taskExecuteDurationUnit=").append(taskExecuteDurationUnit);
        sb.append(", taskExecuteDuration=").append(taskExecuteDuration);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}