package com.newcore.batch.platform.model.po;

import java.io.Serializable;
import java.util.Date;

public class BatchExportTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.batch_export_task_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Long batchExportTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.export_service_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String exportServiceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.export_status
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Integer exportStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.export_opt_clerk_branch_no
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String exportOptClerkBranchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.export_opt_clerk_no
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String exportOptClerkNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.export_opt_clerk_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String exportOptClerkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.export_task_remark
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private String exportTaskRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.export_task_finish_date
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date exportTaskFinishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch_export_task.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.batch_export_task_id
     *
     * @return the value of batch_export_task.batch_export_task_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Long getBatchExportTaskId() {
        return batchExportTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.batch_export_task_id
     *
     * @param batchExportTaskId the value for batch_export_task.batch_export_task_id
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setBatchExportTaskId(Long batchExportTaskId) {
        this.batchExportTaskId = batchExportTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.export_service_name
     *
     * @return the value of batch_export_task.export_service_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getExportServiceName() {
        return exportServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.export_service_name
     *
     * @param exportServiceName the value for batch_export_task.export_service_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setExportServiceName(String exportServiceName) {
        this.exportServiceName = exportServiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.export_status
     *
     * @return the value of batch_export_task.export_status
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Integer getExportStatus() {
        return exportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.export_status
     *
     * @param exportStatus the value for batch_export_task.export_status
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setExportStatus(Integer exportStatus) {
        this.exportStatus = exportStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.export_opt_clerk_branch_no
     *
     * @return the value of batch_export_task.export_opt_clerk_branch_no
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getExportOptClerkBranchNo() {
        return exportOptClerkBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.export_opt_clerk_branch_no
     *
     * @param exportOptClerkBranchNo the value for batch_export_task.export_opt_clerk_branch_no
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setExportOptClerkBranchNo(String exportOptClerkBranchNo) {
        this.exportOptClerkBranchNo = exportOptClerkBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.export_opt_clerk_no
     *
     * @return the value of batch_export_task.export_opt_clerk_no
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getExportOptClerkNo() {
        return exportOptClerkNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.export_opt_clerk_no
     *
     * @param exportOptClerkNo the value for batch_export_task.export_opt_clerk_no
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setExportOptClerkNo(String exportOptClerkNo) {
        this.exportOptClerkNo = exportOptClerkNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.export_opt_clerk_name
     *
     * @return the value of batch_export_task.export_opt_clerk_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getExportOptClerkName() {
        return exportOptClerkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.export_opt_clerk_name
     *
     * @param exportOptClerkName the value for batch_export_task.export_opt_clerk_name
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setExportOptClerkName(String exportOptClerkName) {
        this.exportOptClerkName = exportOptClerkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.export_task_remark
     *
     * @return the value of batch_export_task.export_task_remark
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public String getExportTaskRemark() {
        return exportTaskRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.export_task_remark
     *
     * @param exportTaskRemark the value for batch_export_task.export_task_remark
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setExportTaskRemark(String exportTaskRemark) {
        this.exportTaskRemark = exportTaskRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.export_task_finish_date
     *
     * @return the value of batch_export_task.export_task_finish_date
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getExportTaskFinishDate() {
        return exportTaskFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.export_task_finish_date
     *
     * @param exportTaskFinishDate the value for batch_export_task.export_task_finish_date
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setExportTaskFinishDate(Date exportTaskFinishDate) {
        this.exportTaskFinishDate = exportTaskFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.create_time
     *
     * @return the value of batch_export_task.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.create_time
     *
     * @param createTime the value for batch_export_task.create_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch_export_task.update_time
     *
     * @return the value of batch_export_task.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch_export_task.update_time
     *
     * @param updateTime the value for batch_export_task.update_time
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_export_task
     *
     * @mbggenerated Thu Aug 10 11:10:46 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", batchExportTaskId=").append(batchExportTaskId);
        sb.append(", exportServiceName=").append(exportServiceName);
        sb.append(", exportStatus=").append(exportStatus);
        sb.append(", exportOptClerkBranchNo=").append(exportOptClerkBranchNo);
        sb.append(", exportOptClerkNo=").append(exportOptClerkNo);
        sb.append(", exportOptClerkName=").append(exportOptClerkName);
        sb.append(", exportTaskRemark=").append(exportTaskRemark);
        sb.append(", exportTaskFinishDate=").append(exportTaskFinishDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}